### PR TITLE
Feature/storybook

### PR DESCRIPTION
**Pull request by sebbel**

### CODE REVIEW

**Comment by sebbel** [comment]
Pushing this PR so people could try it on their machines, and get a general idea if we want this or not :)

**Comment by jesperhodge** [comment]
Looks super, using storybook is extremely helpful. Global styles / typography doesn't work yet for the headings - maybe fix that before merge, and I can recommend making an early final decision about CSS structure - e.g. styled components could be awesome here.

Also, I would love to get some advice from you: how do you normally solve the global styles problem with storybook? I'm facing that problem at work now, as we are using CSS modules plus global CSS and our new storybook cannot display global styles right now - that messes up all the typography.

**Comment by sebbel** [comment]
global things always call for trouble. I do like to use styled components

**Comment by lpatmo** [comment]
Ohh, I see storybook at work too, but I haven't set it up before. 

@sebbel Is this article at https://medium.com/encode/setting-up-storybook-with-material-ui-and-styled-components-5bdacb6db866 helpful?

Btw, for others looking to play around -- you'll need to run `npm install` and `npm run storybook` after you check out sebbel's branch.

We're using Material UI in this repo now, so we do have styled components. I'm for storybook, but a little unclear on which components we'd want to highlight in our storybook specifically -- I imagine the list would include common things like `Search`, `Button` and also custom components like `PersonalMenu`. We could even turn this into an ongoing project for any potentially interested contributors.

**Comment by jesperhodge** [comment]
Okay, then I opened https://github.com/codebuddies/react-concept/issues/73, is that good for you?

As for what components should be in storybook: it’s mainly for visual UI components, like buttons and panels and all that stuff. But basically the idea is to build all the visual components isolated in storybook and then putting them into your app. It helps to keep the data fetching and heavy business logic a bit separated.

And I myself am a strong believer of separating business and Ui logic as much as possible to make stuff testable, isolated, and bug free. What is your opinion on that?

**Comment by lpatmo** [comment]
That makes sense to me! I was struggling with the idea of what to put in a design system library when we're mostly borrowing from Material UI -- but I just realized that we _do_ sort of have custom styles built on top of those Material UI components, so whatever we put in there we can start using as a reference for other pages we start building out.

**Comment by sebbel** [comment]
I did add stories for all components @lpatmo

**Comment by lpatmo** [comment]
Yep, I saw! I was thinking of some of the more foundational components -- like dropdown, button, input field, etc. We're using the design system from Material UI, but if we're applying custom styles to e.g. a button we'll want to put that into storybook too, though it doesn't have to be in this PR.

**Comment by jesperhodge** [comment]
Would be awesome if we can merge this pretty soon, I think there is nothing that could speak against having this storybook as an addition, whether it is used a lot or not. I'll also pull it into my branch to see how it works with the MUI components.

**Comment by lpatmo** [comment]
The only thing I might add this to PR are some instructions to the README about how to run storybook using `npm run storybook`, but otherwise happy to merge if there isn't more you want to add too, @sebbel. 

And since I didn't say this before -- thank you for setting all of this up, @sebbel! :)

**Comment by sebbel** [comment]
Added some docs. @lpatmo

**Comment by lpatmo** [comment]
Thank you!! Merging this. :) 

(Sorry for the delay)

**Pull request merged**
